# Generated by Django 3.2.7 on 2021-09-16 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['read']},
        ),
        migrations.RenameField(
            model_name='book',
            old_name='complete',
            new_name='read',
        ),
    ]
