# Generated by Django 3.2.7 on 2021-09-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210916_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='progress',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
