# Generated by Django 3.2.7 on 2021-09-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_book_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='currently_reading',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='to_be_read',
            field=models.BooleanField(default=False),
        ),
    ]
