# Generated by Django 3.2.7 on 2021-09-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210917_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('C', 'Currently Reading'), ('R', 'Read'), ('T', 'To Be Read')], default='T', max_length=1),
        ),
    ]
