# Generated by Django 3.2.7 on 2021-09-17 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_book_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
        migrations.RemoveField(
            model_name='book',
            name='currently_reading',
        ),
        migrations.RemoveField(
            model_name='book',
            name='read',
        ),
        migrations.RemoveField(
            model_name='book',
            name='to_be_read',
        ),
    ]
